stages:
  - build


build-dind-jdk11:
  stage: build
  image: jdrouet/docker-with-buildx:stable
  tags:
    - homelab
  services:
    - docker:18.09.7-dind
  variables:
    DOCKER_DRIVER: overlay
    DOCKER_HOST: tcp://localhost:2375/
  before_script:
    - docker info
  script:
    - docker buildx create --use
    - cd jdk13
    - docker buildx build --platform linux/amd64,linux/arm64 --tag lab.0x09.de:61000/homelab/ksp-luna:0.27.0 .
  only:
    - master
