image: docker:18.09.7

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

services:
  - docker:18.09.7-dind

before_script:
  - docker info

stages:
  - build

build-0.27.0:
  stage: build
  image: jdrouet/docker-with-buildx:stable
  tags:
    - homelab
  script:
    - docker context create homelab
    - cd 0.27.0
    - docker buildx create homelab --use
    - docker buildx build --platform linux/amd64,linux/arm64 --tag lab.0x09.de:61000/homelab/ksp-luna:0.27.0 .
  only:
    - master
