image: docker:19.03.13

variables:
  DOCKER_DRIVER: overlay
  DOCKER_HOST: tcp://localhost:2375/

services:
  - docker:19.03.13-dind

before_script:
  - docker info

stages:
  - build

build-0.27.0:
  stage: build
  image: jdrouet/docker-with-buildx:stable
  tags:
    - homelab
  script:
    - docker buildx create --use
    - cd jdk13
    - docker buildx build --platform linux/amd64,linux/arm64 --tag lab.0x09.de:61000/homelab/ksp-luna:0.27.0 .
  only:
    - master
